### ISSUE TITLE
Download of course does not work

### ISSUE THREAD

**Issue by Banzaci** [codeandcats/eggs-benny#6] opened 2017-05-23 10:11 UTC
I try to download this course: https://egghead.io/courses/higher-order-components-with-functional-patterns-using-recompose "Downloads Finished Successfully" is printed in the terminal, however no files are downloaded.

(It did work to download last week, 2017-05-16)

**Comment by codeandcats** [comment] 2017-05-23 10:20
Hi @Banzaci,

Thanks for letting me know. Unfortunately my egghead.io subscription expired last month and I have no interest in renewing it at this time.

However, if you feel comfortable you're welcome to send me a private email to codeandcats@gmail.com with your egghead credentials and I can debug this for you and maybe even have a fix for you tonight.

Otherwise, if you don't feel comfortable emailing me your details you're welcome to fork the repo, fix it yourself and submit a pull request and I can merge it in.

Hope this helps. 😸

**Comment by codeandcats** [comment] 2017-05-26 22:27
Hi @banzaci,

Did you have any luck with this issue? If you like I can still look at it this weekend. If this is a genuine issue I would like to fix it but cannot do so without access to a Pro User account. If you send me your details (to my email address above) you can trust that I will only use it to address the issue and you can change the password as soon as it's resolved. Otherwise, you're welcome to solve the issue yourself and send me a pull request.

Please let me know how you wish to proceed, otherwise I'll close the issue.

**Comment by codeandcats** [comment] 2017-05-28 04:35
Cannot reproduce.

**Closed as completed by codeandcats** 2017-05-28 04:35 UTC
